version: '3.8'

services:
  postgres-wine:
    image: postgres:16
    container_name: postgres-wine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_wine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    #      - ./postgres-data:/var/lib/postgresql/data
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_wine" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
